name: Generate Maven SBOM

on:
  workflow_run:
    workflows: [Maven Release]
    types: [completed]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 'main'
        required: true

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'
  PRODUCT_PATH: './'
  PLUGIN_VERSION: '2.7.8'
  SBOM_TYPE: 'makeAggregateBom'

permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha || github.event.inputs.version }}

      - name: Setup Java SDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Generate sbom
        run: |
          mvn org.cyclonedx:cyclonedx-maven-plugin:$PLUGIN_VERSION:$SBOM_TYPE -f "$PRODUCT_PATH/pom.xml"

      - name: Extract product version
        id: version
        shell: bash
        run: |
          VERSION="$(jq -r '.metadata.component.version' < ${{ env.PRODUCT_PATH }}/target/bom.json)"
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Product version is: $VERSION"

      - name: Upload sbom
        uses: eclipse-csi/workflows/upload-sbom@20e3c63807b2bd61b7f1a9f438e5ce588c054efc # main
        with:
          sbom-file: ${{ env.PRODUCT_PATH }}/target/bom.json
          product-name: 'milo'
          product-version: ${{ steps.version.outputs.PROJECT_VERSION }}
